name: GitHub Actions Demo
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: NPM Install
        run: |
          npm ci

      - name: NPM Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test --verbose --maxWorkers=2